# This is a basic workflow that is manually triggered

name: RXDataUnpacker

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
  ## Only trigger when pull request has rxdata changes.
    paths:
    - '**.rxdata'
jobs:
  create_branch:
    runs-on: ubuntu/latest
    steps:
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ github.event.pull_request.branch.name + '_unpacked'}}
        sha: '${{ github.event.pull_request.head.sha }}'
    
    
